export enum Path {
  Home = '/',
  Explore = '/explore',
  Volunteering = '/volunteering',
  Wishes = '/wishes',
  Donate = '/donate',
  HomeAI = '/ai',
  Response = '/response',
  Stories = '/stories',
  About = '/about-us',
  Faq = '/about-us/faq',
  Contact = '/contact',
  SignUp = '/sign-up',
  LogIn = '/log-in',
  Profile = '/profile',
  ProfileInfo = '/profile/info',
  Activity = '/profile/activity',
  Opportunities = '/profile/opportunities',
  StepOne = '/profile/opportunities/step-one',
  StepTwo = '/profile/opportunities/step-two',
  StepThree = '/profile/opportunities/step-three',
  SuccessSubmit = '/profile/success-submit',
  Menu = '/menu',
}
